# Generated by Django 2.2.5 on 2020-03-26 18:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_no', models.CharField(max_length=12)),
                ('collection', models.CharField(max_length=15)),
                ('unit', models.CharField(max_length=6)),
                ('id_no', models.CharField(max_length=6, verbose_name='ID')),
                ('sector', models.CharField(blank=True, max_length=50, null=True)),
                ('analytical_level', models.CharField(blank=True, max_length=50, null=True)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=25, null=True)),
                ('exc_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('excavator', models.CharField(blank=True, max_length=50, null=True)),
                ('points', django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, null=True, srid=-1)),
            ],
            options={
                'verbose_name': 'FC Context',
                'verbose_name_plural': 'FC Context (Catalog)',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Excavation_unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=6)),
                ('extent', django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, null=True, srid=-1)),
            ],
            options={
                'verbose_name': 'FC Excavation Unit',
                'verbose_name_plural': 'FC Excavation units',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Refits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=6)),
                ('id_no', models.CharField(max_length=6, verbose_name='ID')),
                ('counter', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'FC Refit',
                'verbose_name_plural': 'FC Refits',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Fauna',
            fields=[
                ('context_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fc.Context')),
                ('tentative_ID', models.CharField(blank=True, max_length=20, null=True)),
                ('genus', models.CharField(blank=True, max_length=30, null=True)),
                ('side', models.CharField(blank=True, max_length=5, null=True)),
                ('part', models.CharField(blank=True, max_length=30, null=True)),
                ('portion', models.CharField(blank=True, max_length=30, null=True)),
                ('segment', models.CharField(blank=True, max_length=30, null=True)),
                ('bone_type', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'FC Fauna',
                'verbose_name_plural': 'FC Fauna',
                'managed': True,
            },
            bases=('fc.context',),
        ),
        migrations.CreateModel(
            name='Galet_Weights',
            fields=[
                ('context_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fc.Context')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'FC Galet Weight',
                'verbose_name_plural': 'FC Galet Weights',
                'managed': True,
            },
            bases=('fc.context',),
        ),
        migrations.CreateModel(
            name='Lithic',
            fields=[
                ('context_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fc.Context')),
                ('dataclass', models.CharField(max_length=20)),
                ('raw_material', models.CharField(blank=True, max_length=20, null=True)),
                ('support', models.CharField(blank=True, max_length=20, null=True)),
                ('technique', models.CharField(blank=True, max_length=20, null=True)),
                ('form', models.CharField(blank=True, max_length=20, null=True)),
                ('fb_type', models.IntegerField(blank=True, null=True, verbose_name='Bordes Type')),
                ('fb_type_2', models.IntegerField(blank=True, null=True, verbose_name='Bordes Type 2')),
                ('core_type', models.CharField(blank=True, max_length=20, null=True)),
                ('biface_type', models.CharField(blank=True, max_length=20, null=True)),
                ('retouched_edges', models.IntegerField(blank=True, null=True)),
                ('retouch_intensity', models.CharField(blank=True, max_length=20, null=True)),
                ('tf_character', models.CharField(blank=True, max_length=20, null=True)),
                ('tf_surface', models.CharField(blank=True, max_length=20, null=True)),
                ('tf_location', models.CharField(blank=True, max_length=20, null=True)),
                ('platform_surface', models.CharField(blank=True, max_length=20, null=True)),
                ('platform_exterior', models.CharField(blank=True, max_length=20, null=True)),
                ('core_faces', models.IntegerField(blank=True, null=True)),
                ('platforms', models.CharField(blank=True, max_length=20, null=True)),
                ('platform_technique_1', models.CharField(blank=True, max_length=20, null=True)),
                ('platform_technique_2', models.CharField(blank=True, max_length=20, null=True)),
                ('scar_morphology', models.CharField(blank=True, max_length=20, null=True)),
                ('cortex', models.CharField(blank=True, max_length=12, null=True)),
                ('discard', models.CharField(blank=True, max_length=20, null=True)),
                ('edge_damage', models.CharField(blank=True, max_length=20, null=True)),
                ('alteration', models.CharField(blank=True, max_length=20, null=True)),
                ('proximal_removals', models.IntegerField(blank=True, null=True)),
                ('scar_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('platform_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('platform_thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('small_pw', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bulb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('epa', models.IntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'FC Lithic',
                'verbose_name_plural': 'FC Lithics',
                'managed': True,
            },
            bases=('fc.context',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('context_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fc.Context')),
                ('image01', models.ImageField(blank=True, null=True, upload_to='fc/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'FC Image',
                'verbose_name_plural': 'FC Images',
                'managed': True,
            },
            bases=('fc.context',),
        ),
        migrations.CreateModel(
            name='Small_Find',
            fields=[
                ('context_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fc.Context')),
                ('screen_size', models.CharField(blank=True, max_length=20, null=True)),
                ('platform_count', models.IntegerField(blank=True, null=True)),
                ('platform_weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'FC Small find (bucket)',
                'verbose_name_plural': 'FC Small Finds (Summary Counts by bucket)',
                'managed': True,
            },
            bases=('fc.context',),
        ),
        migrations.CreateModel(
            name='Small_Find_Weights',
            fields=[
                ('smalls_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fc.Context')),
            ],
            options={
                'verbose_name': 'FC artifact in a bucket',
                'verbose_name_plural': 'FC Small Finds (Weights by piece)',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Granulometry',
            fields=[
                ('grain_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fc.Context')),
            ],
            options={
                'verbose_name': 'FC stone in a granulometry bucket',
                'verbose_name_plural': 'FC Granulometry',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Buckets_with_Grains',
            fields=[
            ],
            options={
                'verbose_name': 'FC Bucket with Granulometry',
                'verbose_name_plural': 'FC Buckets with Granulometry',
                'managed': True,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fc.context',),
        ),
        migrations.CreateModel(
            name='Lithics_with_Photos',
            fields=[
            ],
            options={
                'verbose_name': 'FC Lithic (only with photo)',
                'verbose_name_plural': 'FC Lithics (only with photos)',
                'managed': True,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fc.context',),
        ),
        migrations.CreateModel(
            name='Small_find_weights_summary',
            fields=[
            ],
            options={
                'verbose_name': 'FC Weights of small finds in a bucket',
                'verbose_name_plural': 'FC Small Finds (Weights by bucket)',
                'managed': True,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('fc.context',),
        ),
    ]
