# Generated by Django 2.2.13 on 2020-06-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='app_label',
            field=models.CharField(blank=True, choices=[('mlp', 'mlp'), ('drp', 'drp')], max_length=100, null=True),
        ),
    ]
