# Generated by Django 2.2.5 on 2020-03-27 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('omo_mursi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='field_number',
            new_name='date_recorded',
        ),
    ]
