# Generated by Django 2.2.5 on 2020-03-27 22:54

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('omo_mursi', '0002_auto_20200327_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this resource was first created.', verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='field_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='last_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='barcode',
            field=models.IntegerField(blank=True, help_text='For collected items only.', null=True, verbose_name='Barcode'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='date_last_modified',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time this resource was last altered.', verbose_name='Modified'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='date_recorded',
            field=models.DateTimeField(blank=True, help_text='Date and time the item was observed or collected.', null=True, verbose_name='Date Rec'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='problem',
            field=models.BooleanField(default=False, help_text='Is there a problem with this record that needs attention?'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='problem_comment',
            field=models.TextField(blank=True, help_text='Description of the problem.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='remarks',
            field=ckeditor.fields.RichTextField(blank=True, help_text='General remarks about this database record.', null=True, verbose_name='Record Remarks'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='year_collected',
            field=models.IntegerField(blank=True, help_text='The year, event or field campaign during which the item was found.', null=True, verbose_name='Year'),
        ),
    ]
