# Generated by Django 2.2.13 on 2020-10-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('origins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='location_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
