# Generated by Django 2.2.13 on 2020-06-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='field_season',
            field=models.CharField(blank=True, choices=[('January 2014', 'Jan 2014'), ('Nov 2014', 'Nov 2014'), ('Nov 2015', 'Nov 2015'), ('Jan 2018', 'Jan 2018'), ('Jan 2019', 'Jan 2019'), ('Jan 2020', 'Jan 2020')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='item_type',
            field=models.CharField(blank=True, choices=[('Artifactual', 'Artifactual'), ('Faunal', 'Faunal'), ('Floral', 'Floral'), ('Geological', 'Geological'), ('Cast', 'Cast')], max_length=255, verbose_name='Item Type'),
        ),
    ]
