# Generated by Django 2.2.13 on 2021-01-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlp', '0002_auto_20200612_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='stratigraphic_formation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Formation'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='stratigraphic_member',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Member'),
        ),
    ]
