# Generated by Django 2.2.13 on 2020-07-10 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identificationqualifier',
            options={'verbose_name': 'PSR ID Qualifier', 'verbose_name_plural': 'PSR ID Qualifiers'},
        ),
        migrations.AlterModelOptions(
            name='locality',
            options={'ordering': ('locality_number', 'sublocality'), 'verbose_name': 'PSR Locality', 'verbose_name_plural': 'PSR Localities'},
        ),
        migrations.AlterModelOptions(
            name='occurrence',
            options={'ordering': ['collection_code', 'locality', 'item_number', 'item_part'], 'verbose_name': 'PSR Occurrence', 'verbose_name_plural': 'PSR Occurrences'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'PSR Person', 'verbose_name_plural': 'PSR People'},
        ),
        migrations.AlterModelOptions(
            name='taxon',
            options={'verbose_name': 'PSR Taxon', 'verbose_name_plural': 'PSR Taxa'},
        ),
        migrations.RemoveField(
            model_name='biology',
            name='qualifier_taxon',
        ),
        migrations.AlterField(
            model_name='biology',
            name='identification_qualifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bio_occurrences', to='psr.IdentificationQualifier'),
        ),
        migrations.AlterField(
            model_name='biology',
            name='taxon',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='bio_occurrences', to='psr.Taxon'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/images')),
                ('description', models.TextField(blank=True, null=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psr_occurrences', to='psr.Occurrence')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/files')),
                ('description', models.TextField(blank=True, null=True)),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psr.Occurrence')),
            ],
        ),
    ]
