# Generated by Django 2.2.13 on 2020-07-14 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0002_auto_20200710_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aggregate',
            fields=[
                ('occurrence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='psr.Occurrence')),
                ('screen_size', models.CharField(blank=True, max_length=255, null=True)),
                ('counts', models.IntegerField(blank=True, null=True)),
                ('weights', models.IntegerField(blank=True, null=True)),
                ('bull_find_remarks', models.TextField(blank=True, max_length=64000, null=True)),
            ],
            options={
                'verbose_name': 'PSR Bulk Find',
                'verbose_name_plural': 'PSR Bulk Finds',
            },
            bases=('psr.occurrence',),
        ),
        migrations.RenameField(
            model_name='archaeology',
            old_name='find_type',
            new_name='archaeology_type',
        ),
        migrations.AddField(
            model_name='archaeology',
            name='archaeology_preparation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archaeology',
            name='archaeology_remarks',
            field=models.TextField(blank=True, max_length=64000, null=True),
        ),
        migrations.AddField(
            model_name='archaeology',
            name='period',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
