# Generated by Django 2.2.13 on 2020-08-06 14:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psr', '0004_auto_20200803_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geology',
            old_name='find_type',
            new_name='geology_type',
        ),
        migrations.RemoveField(
            model_name='cave',
            name='find_type',
        ),
        migrations.RemoveField(
            model_name='occurrence',
            name='specimen_id',
        ),
        migrations.AddField(
            model_name='biology',
            name='biology_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bone',
            name='burning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bone',
            name='part',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ceramic',
            name='decorated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='locality',
            name='find_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='field_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Field ID'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='point',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, null=True, srid=-1),
        ),
        migrations.AlterField(
            model_name='locality',
            name='name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locality',
            name='upper_limit_in_section',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=38, null=True),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='field_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
