# Generated by Django 2.2.13 on 2020-06-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0002_auto_20200612_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='abcd',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
