# Generated by Django 2.2.13 on 2020-06-12 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0003_auto_20200612_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='abcd',
            field=models.TextField(blank=True, null=True),
        ),
    ]
