# Generated by Django 2.2.13 on 2020-06-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0005_termsindexpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='term',
            old_name='example',
            new_name='examples',
        ),
    ]
