# Generated by Django 2.2.13 on 2020-07-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0006_auto_20200625_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='class_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='standard.Term'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(blank=True, help_text='A short (one to two word) name for the project, e.g. Hadar', max_length=20, null=True),
        ),
    ]
