# Generated by Django 2.2.13 on 2020-07-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0007_auto_20200707_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='class_category',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_class': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='standard.Term'),
        ),
    ]
