# Generated by Django 2.2.13 on 2020-07-07 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0008_auto_20200707_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='appname',
            new_name='app_name',
        ),
    ]
