# Generated by Django 2.2.13 on 2020-07-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0010_termsindexpage_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='is_subclass',
            field=models.BooleanField(default=False),
        ),
    ]
