# Generated by Django 2.2.13 on 2020-07-13 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standard', '0012_termsindexpage_project_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termsindexpage',
            old_name='project_code',
            new_name='project',
        ),
    ]
