HRP_COLLECTOR_CHOICES = (("C.J. Campisano", "C.J. Campisano"),
                         ("W.H. Kimbel", "W.H. Kimbel"),
                         ("T.K. Nalley", "T.K. Nalley"),
                         ("D.N. Reed", "D.N. Reed"),
                         ("Kaye Reed", "Kaye Reed"),
                         ("B.J. Schoville", "B.J. Schoville"),
                         ("A.E. Shapiro", "A.E. Shapiro"),
                         ("HFS Student", "HFS Student"),
                         ("HRP Team", "HRP Team")
                         )


HRP_COLLECTION_CODES = (("A.L.", "A.L."),)


ITEM_TYPE_VOCABULARY = (("Artifactual", "Artifactual"), ("Faunal", "Faunal"), ("Floral", "Floral"), ("Geological", "Geological"))

HRP_COLLECTING_METHOD_VOCABULARY = (("Survey", "Survey"),
                                ("dryscreen5mm", "dryscreen5mm"),
                                ("wetscreen1mm", "wetscreen1mm"))

HRP_BASIS_OF_RECORD_VOCABULARY = (("Collection", "Collection"), ("Observation", "Observation"))

HRP_ELEMENT_STANDARD = (
    ('astragalus', 'astragalus'),
    ('bacculum', 'bacculum'),
    ('bone (indet.)', 'bone (indet.)'),
    ('calcaneus', 'calcaneus'),
    ('canine', 'canine'),
    ('capitate', 'capitate'),
    ('carapace', 'carapace'),
    ('carpal (indet.)', 'carpal (indet.)'),
    ('carpal/tarsal', 'carpal/tarsal'),
    ('carpometacarpus', 'carpometacarpus'),
    ('carpus', 'carpus'),
    ('chela', 'chela'),
    ('clavicle', 'clavicle'),
    ('coccyx', 'coccyx'),
    ('coprolite', 'coprolite'),
    ('cranium', 'cranium'),
    ('cranium w/horn core', 'cranium w/horn core'),
    ('cuboid', 'cuboid'),
    ('cubonavicular', 'cubonavicular'),
    ('cuneiform', 'cuneiform'),
    ('dermal plate', 'dermal plate'),
    ('egg shell', 'egg shell'),
    ('endocast', 'endocast'),
    ('ethmoid', 'ethmoid'),
    ('femur', 'femur'),
    ('fibula', 'fibula'),
    ('frontal', 'frontal'),
    ('hamate', 'hamate'),
    ('horn core', 'horn core'),
    ('humerus', 'humerus'),
    ('hyoid', 'hyoid'),
    ('Ilium', 'Ilium'),
    ('incisor', 'incisor'),
    ('innominate', 'innominate'),
    ('ischium', 'ischium'),
    ('lacrimal', 'lacrimal'),
    ('long bone ', 'long bone '),
    ('lunate', 'lunate'),
    ('mandible', 'mandible'),
    ('manus', 'manus'),
    ('maxilla', 'maxilla'),
    ('metacarpal', 'metacarpal'),
    ('metapodial', 'metapodial'),
    ('metatarsal', 'metatarsal'),
    ('molar', 'molar'),
    ('nasal', 'nasal'),
    ('navicular', 'navicular'),
    ('naviculocuboid', 'naviculocuboid'),
    ('occipital', 'occipital'),
    ('ossicone', 'ossicone'),
    ('parietal', 'parietal'),
    ('patella', 'patella'),
    ('pes', 'pes'),
    ('phalanx', 'phalanx'),
    ('pisiform', 'pisiform'),
    ('plastron', 'plastron'),
    ('premaxilla', 'premaxilla'),
    ('premolar', 'premolar'),
    ('pubis', 'pubis'),
    ('radioulna', 'radioulna'),
    ('radius', 'radius'),
    ('rib', 'rib'),
    ('sacrum', 'sacrum'),
    ('scaphoid', 'scaphoid'),
    ('scapholunar', 'scapholunar'),
    ('scapula', 'scapula'),
    ('scute', 'scute'),
    ('sesamoid', 'sesamoid'),
    ('shell', 'shell'),
    ('skeleton', 'skeleton'),
    ('skull', 'skull'),
    ('sphenoid', 'sphenoid'),
    ('sternum', 'sternum'),
    ('talon', 'talon'),
    ('talus', 'talus'),
    ('tarsal (indet.)', 'tarsal (indet.)'),
    ('tarsometatarsus', 'tarsometatarsus'),
    ('tarsus', 'tarsus'),
    ('temporal', 'temporal'),
    ('tibia', 'tibia'),
    ('tibiotarsus', 'tibiotarsus'),
    ('tooth (indet.)', 'tooth (indet.)'),
    ('trapezium', 'trapezium'),
    ('trapezoid', 'trapezoid'),
    ('triquetrum', 'triquetrum'),
    ('ulna', 'ulna'),
    ('vertebra', 'vertebra'),
    ('vomer', 'vomer'),
    ('zygomatic', 'zygomatic'),
)

HRP_ELEMENT_ADDITIONAL = (('pharyngeal teeth', 'pharyngeal teeth'),
                          ('molars', 'molars'),
                          ('tusk', 'tusk'),
                          ('horn corn', 'horn corn'),
                          ('spine', 'spine'),
                          ('silicified wood', 'silicified wood'),
                          ('dentary', 'dentary'),
                          ('cleithrum', 'cleithrum'),
                          ('skull plate', 'skull plate'),
                          ('basicranium', 'basicranium'),
                          ('angulararticular', 'angulararticular'),
                          ('ribs', 'ribs'),
                          ('lateral ethmoid', 'lateral ethmoid'),
                          ('pterotic', 'pterotic'),
                          ('tooth roots', 'tooth roots'),
                          ('shells', 'shells'),
                          ('pharyngeal tooth', 'pharyngeal tooth'),
                          ('ilium', 'ilium'),
                          ('hemimandible', 'hemimandible'),
                          ('pectoral spine', 'pectoral spine'),
                          ('palate', 'palate'),
                          ('pelvis', 'pelvis'),
                          ('long bone', 'long bone'),
                          ('axis', 'axis'),
                          ('acetabulum', 'acetabulum'),
                          ('magnum', 'magnum'),
                          ('hemi-mandible', 'hemi-mandible'),
                          ('weberian', 'weberian'),
                          ('supraoccipital', 'supraoccipital'),
                          ('anguloarticular', 'anguloarticular')
                          )

HRP_ELEMENT_CHOICES = HRP_ELEMENT_STANDARD + HRP_ELEMENT_ADDITIONAL

HRP_ELEMENT_PORTION_CHOICES = (
    ('almost complete', 'almost complete'),
    ('anterior', 'anterior'),
    ('basal', 'basal'),
    ('caudal', 'caudal'),
    ('complete', 'complete'),
    ('cranial', 'cranial'),
    ('diaphysis', 'diaphysis'),
    ('diaphysis+distal', 'diaphysis+distal'),
    ('diaphysis+proximal', 'diaphysis+proximal'),
    ('distal', 'distal'),
    ('dorsal', 'dorsal'),
    ('epiphysis', 'epiphysis'),
    ('fragment', 'fragment'),
    ('fragments', 'fragments'),
    ('indeterminate', 'indeterminate'),
    ('lateral', 'lateral'),
    ('medial', 'medial'),
    ('midsection', 'midsection'),
    ('midsection+basal', 'midsection+basal'),
    ('midsection+distal', 'midsection+distal'),
    ('posterior', 'posterior'),
    ('proximal', 'proximal'),
    ('symphysis', 'symphysis'),
    ('ventral', 'ventral'),
)

HRP_ELEMENT_NUMBER_CHOICES = (
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('3(medial)', '3(medial)'),
    ('4', '4'),
    ('4(lateral)', '4(lateral)'),
    ('5', '5'),
    ('6', '6'),
    ('7', '7'),
    ('8', '8'),
    ('9', '9'),
    ('10', '10'),
    ('11', '11'),
    ('12', '12'),
    ('13', '13'),
    ('14', '14'),
    ('15', '15'),
    ('16', '16'),
    ('17', '17'),
    ('2-7', '2-7'),
    ('8-12', '8-12'),
    ('indeterminate', 'indeterminate'),
)

HRP_ELEMENT_MODIFIER_CHOICES = (
    ('articulated', 'articulated'),
    ('caudal', 'caudal'),
    ('cervical', 'cervical'),
    ('coccygeal', 'coccygeal'),
    ('distal', 'distal'),
    ('intermediate', 'intermediate'),
    ('lower', 'lower'),
    ('lumbar', 'lumbar'),
    ('manual', 'manual'),
    ('manual distal', 'manual distal'),
    ('manual intermediate', 'manual intermediate'),
    ('manual proximal', 'manual proximal'),
    ('medial', 'medial'),
    ('pedal', 'pedal'),
    ('pedal distal', 'pedal distal'),
    ('pedal intermediate', 'pedal intermediate'),
    ('pedal proximal', 'pedal proximal'),
    ('proximal', 'proximal'),
    ('sacral', 'sacral'),
    ('thoracic', 'thoracic'),
    ('upper', 'upper'),
    ('indeterminate', 'indeterminate')
)

HRP_SIDE_CHOICES = (
    (u'L', u'L'),
    (u'R', u'R'),
    (u'Indeterminate', u'Indeterminate'),
    (u'L+R', u'L+R')
)

HRP_LIFE_STAGE_CHOICES = (
    ('infant', 'infant'),
    ('juvenile', 'juvenile')
)

HRP_SIZE_CLASS_CHOICES = (
    ('indeterminate', 'indeterminate'),
    ('1', '1'),
    ('2', '2'),
    ('3', '3'),
    ('4', '4'),
    ('5', '5')
)

HRP_IDENTIFIER_CHOICES = (('Z. Alemseged', 'Z. Alemseged'),
                          ('R.L. Bernor', 'R.L. Bernor'),
                          ('R. Bobe-Quinteros', 'R. Bobe-Quinteros'),
                          ('P. Brodkorb', 'P. Brodkorb'),
                          ('H.B.S. Cooke', 'H.B.S. Cooke'),
                          ('E. Delson', 'E. Delson'),
                          ('C. Denys', 'C. Denys'),
                          ('G.G. Eck', 'G.G. Eck'),
                          ('V. Eisenmann', 'V. Eisenmann'),
                          ('N. Fessaha', 'N. Fessaha'),
                          ('L.J. Flynn', 'L.J. Flynn'),
                          ('S.R. Frost', 'S.R. Frost'),
                          ('A.W. Gentry', 'A.W. Gentry'),
                          ('D. Geraads', 'D. Geraads'),
                          ('R. Geze', 'R. Geze'),
                          ('F.C. Howell', 'F.C. Howell'),
                          ('Institute Staff', 'Institute Staff'),
                          ('D.C. Johanson', 'D.C. Johanson'),
                          ('W.H. Kimbel', 'W.H. Kimbel'),
                          ('H.B. Krentza', 'H.B. Krentza'),
                          ('B.M. Latimer', 'B.M. Latimer'),
                          ('M.E. Lewis', 'M.E. Lewis'),
                          ('C.A. Lockwood', 'C.A. Lockwood'),
                          ('T.K. Nalley', 'T.K. Nalley'),
                          ('G. Petter', 'G. Petter'),
                          ('J.C. Rage', 'J.C. Rage'),
                          ('D. Reed', 'D. Reed'),
                          ('K.E. Reed', 'K.E. Reed'),
                          ('J. Rowan', 'J. Rowan'),
                          ('M. Sabatier', 'M. Sabatier'),
                          ('B.J. Schoville', 'B.J. Schoville'),
                          ('A.E. Shapiro', 'A.E. Shapiro'),
                          ('G. Suwa', 'G. Suwa'),
                          ('E.S. Vrba', 'E.S. Vrba'),
                          ('L.A. Werdelin', 'L.A. Werdelin'),
                          ('H.B. Wesselman', 'H.B. Wesselman'),
                          ('T.D. White', 'T.D. White'),
                          )
