# Generated by Django 2.2.13 on 2020-06-12 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lgrp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrence',
            name='item_type',
            field=models.CharField(blank=True, choices=[('Artifactual', 'Artifactual'), ('Faunal', 'Faunal'), ('Floral', 'Floral'), ('Geological', 'Geological'), ('Cast', 'Cast')], max_length=255, verbose_name='Item Type'),
        ),
    ]
