# Generated by Django 2.2.5 on 2020-03-30 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20180607_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='state_province',
            field=models.CharField(blank=True, max_length=10, verbose_name='State or Province'),
        ),
    ]
