# Generated by Django 2.2.13 on 2020-09-14 23:01

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_personpage_orcid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('last', models.CharField(blank=True, max_length=255, null=True)),
                ('first', models.CharField(blank=True, max_length=255, null=True)),
                ('orcid', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_rank', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.TextField(blank=True, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=255, null=True)),
                ('graduating_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('advisor', models.CharField(blank=True, max_length=255, null=True)),
                ('major_works', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('remarks', wagtail.core.fields.RichTextField(blank=True, null=True)),
                ('other', wagtail.core.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
    ]
