# Generated by Django 2.2.13 on 2020-09-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='biblio',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
