# Generated by Django 2.2.5 on 2020-03-26 17:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_no', models.CharField(max_length=12)),
                ('unit', models.CharField(max_length=6)),
                ('id_no', models.CharField(max_length=6, verbose_name='ID')),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=25, null=True)),
                ('excavator', models.CharField(blank=True, max_length=50, null=True)),
                ('exc_date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('exc_time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('points', django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, null=True, srid=-1)),
            ],
            options={
                'verbose_name': 'cc Context',
                'verbose_name_plural': 'cc Context (Catalog)',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExcavationUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=6)),
                ('extent', django.contrib.gis.db.models.fields.GeometryField(blank=True, dim=3, null=True, srid=-1)),
            ],
            options={
                'verbose_name': 'Excavation Unit',
                'verbose_name_plural': 'Excavation units',
                'db_table': 'cc_excavation_unit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Lithic',
            fields=[
                ('context_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cc.Context')),
                ('dataclass', models.CharField(blank=True, max_length=20, null=True)),
                ('cortex', models.CharField(blank=True, max_length=10, null=True)),
                ('technique', models.CharField(blank=True, max_length=20, null=True)),
                ('alteration', models.CharField(blank=True, max_length=20, null=True)),
                ('edge_damage', models.CharField(blank=True, max_length=20, null=True)),
                ('fb_type', models.IntegerField(blank=True, null=True, verbose_name='Bordes Type')),
                ('fb_type_2', models.IntegerField(blank=True, null=True, verbose_name='Bordes Type 2')),
                ('fb_type_3', models.IntegerField(blank=True, null=True, verbose_name='Bordes Type 3')),
                ('platform_surface', models.CharField(blank=True, max_length=20, null=True)),
                ('platform_exterior', models.CharField(blank=True, max_length=20, null=True)),
                ('form', models.CharField(blank=True, max_length=20, null=True)),
                ('scar_morphology', models.CharField(blank=True, max_length=20, null=True)),
                ('retouched_edges', models.IntegerField(blank=True, null=True)),
                ('retouch_intensity', models.CharField(blank=True, max_length=20, null=True)),
                ('reprise', models.CharField(blank=True, max_length=20, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maximum_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('platform_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('platform_thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('raw_material', models.CharField(blank=True, max_length=20, null=True)),
                ('exterior_surface', models.CharField(blank=True, max_length=20, null=True)),
                ('exterior_type', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('platform_technique', models.CharField(blank=True, max_length=20, null=True)),
                ('platform_angle', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('multiple', models.NullBooleanField(default=False)),
                ('epa', models.IntegerField(blank=True, null=True)),
                ('core_shape', models.CharField(blank=True, max_length=20, null=True)),
                ('core_blank', models.CharField(blank=True, max_length=20, null=True)),
                ('core_surface_percentage', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('proximal_removals', models.IntegerField(blank=True, null=True)),
                ('prepared_platforms', models.IntegerField(blank=True, null=True)),
                ('flake_direction', models.CharField(blank=True, max_length=20, null=True)),
                ('scar_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scar_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'cc Lithic',
                'verbose_name_plural': 'cc Lithics',
                'managed': True,
            },
            bases=('cc.context',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('context_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cc.Context')),
                ('image01', models.ImageField(blank=True, null=True, upload_to='cc/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'cc Image',
                'verbose_name_plural': 'cc Images',
                'managed': True,
            },
            bases=('cc.context',),
        ),
        migrations.CreateModel(
            name='SmallFind',
            fields=[
                ('context_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cc.Context')),
                ('coarse_stone_weight', models.IntegerField(blank=True, null=True)),
                ('coarse_fauna_weight', models.IntegerField(blank=True, null=True)),
                ('fine_stone_weight', models.IntegerField(blank=True, null=True)),
                ('fine_fauna_weight', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'cc Small find (bucket)',
                'verbose_name_plural': 'cc Small finds (buckets)',
                'db_table': 'cc_small_find',
                'managed': True,
            },
            bases=('cc.context',),
        ),
        migrations.CreateModel(
            name='LithicsWithPhotos',
            fields=[
            ],
            options={
                'verbose_name': 'cc Lithic (only with photo)',
                'verbose_name_plural': 'cc Lithics (only with photos)',
                'managed': True,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cc.context',),
        ),
    ]
