# Generated by Django 2.2.13 on 2020-08-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('example', models.CharField(blank=True, max_length=255, null=True)),
                ('example_taxon', models.CharField(blank=True, max_length=255, null=True)),
                ('geography', models.CharField(blank=True, max_length=255, null=True)),
                ('commentsFS', models.TextField(blank=True, null=True)),
                ('commentsSP', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('geography', 'code'),
            },
        ),
    ]
