# Generated by Django 2.2.5 on 2020-03-30 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='occurrence',
            options={},
        ),
    ]
