# Generated by Django 2.2.13 on 2020-06-12 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtap', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Archaeology',
            new_name='Artifact',
        ),
    ]
