# Generated by Django 2.2.13 on 2020-06-12 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtap', '0002_auto_20200612_0357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biology',
            new_name='Fossil',
        ),
        migrations.RenameModel(
            old_name='Geology',
            new_name='Rock',
        ),
    ]
