# Generated by Django 2.2.13 on 2020-06-12 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtap', '0003_auto_20200612_0400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifact',
            options={'verbose_name': 'WTAP Artifact', 'verbose_name_plural': 'WTAP Artifacts'},
        ),
        migrations.AlterModelOptions(
            name='fossil',
            options={'verbose_name': 'WTAP Fossil', 'verbose_name_plural': 'WTAP Fossils'},
        ),
        migrations.AlterModelOptions(
            name='rock',
            options={'verbose_name': 'WTAP Rock', 'verbose_name_plural': 'WTAP Rocks'},
        ),
        migrations.AddField(
            model_name='artifact',
            name='alteration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='artifact_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='core_blank',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='core_shape',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='core_surface_percentage',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='cortex',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='edge_damage',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='epa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='exterior_surface',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='exterior_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='fb_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bordes Type'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='fb_type_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bordes Type 2'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='fb_type_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Bordes Type 3'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='flake_direction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='form',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='maximum_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='multiple',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artifact',
            name='platform_angle',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='platform_exterior',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='platform_surface',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='platform_technique',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='platform_thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='platform_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='prepared_platforms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='proximal_removals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='raw_material',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='reprise',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='retouch_intensity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='retouched_edges',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='scar_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='scar_morphology',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='scar_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='technique',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='artifact',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='length_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='artifact',
            name='width_mm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
